# Generated by Django 3.2.3 on 2021-06-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_category_color'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
