# Generated by Django 3.1.3 on 2021-06-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catgory',
            new_name='category',
        ),
    ]
